import type { Account, AppPermission, PasswordCluster, PermissionDefinition } from '../types/account';

export const PERMISSION_DEFINITIONS: Record<AppPermission, PermissionDefinition> = {
  camera: {
    id: 'camera',
    label: 'Camera Access',
    iconName: 'Camera',
    riskWeight: 6,
    description: 'Allows capturing photo and video recording without prior active prompt.',
  },
  microphone: {
    id: 'microphone',
    label: 'Microphone & Audio',
    iconName: 'Mic',
    riskWeight: 7,
    description: 'Allows recording ambient sound and voice conversations.',
  },
  precise_location: {
    id: 'precise_location',
    label: 'Precise GPS Location',
    iconName: 'MapPin',
    riskWeight: 8,
    description: 'Tracks continuous real-time geographical coordinates.',
  },
  contacts: {
    id: 'contacts',
    label: 'Contacts & Address Book',
    iconName: 'Users',
    riskWeight: 7,
    description: 'Reads your full contacts list, phone numbers, and social connections.',
  },
  photos_storage: {
    id: 'photos_storage',
    label: 'Photos & Local Files',
    iconName: 'FolderArchive',
    riskWeight: 6,
    description: 'Reads stored media, documents, and downloaded attachments.',
  },
  financial_data: {
    id: 'financial_data',
    label: 'Financial & Card Data',
    iconName: 'CreditCard',
    riskWeight: 9,
    description: 'Stores payment methods, transaction records, or credit history.',
  },
  background_tracking: {
    id: 'background_tracking',
    label: 'Background Execution & Tracking',
    iconName: 'Activity',
    riskWeight: 8,
    description: 'Runs persistently when app is closed to harvest telemetry.',
  },
};

export const INITIAL_PASSWORD_CLUSTERS: PasswordCluster[] = [
  {
    id: 'cluster_legacy_easy',
    label: 'Legacy Shared (High Risk)',
    color: '#ef4444', // Red
    description: 'Reused across older accounts created before password manager adoption',
  },
  {
    id: 'cluster_casual_shopping',
    label: 'Casual Services Cluster',
    color: '#f59e0b', // Amber
    description: 'Reused across shopping & media subscription portals',
  },
  {
    id: 'cluster_unique_vault',
    label: 'Unique / Vault Generated',
    color: '#10b981', // Emerald
    description: 'Generated 20+ character random unique passwords',
  },
];

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc_google_primary',
    name: 'Google (Personal Primary)',
    serviceCategory: 'identity_email',
    usernameOrEmail: 'alex.morgan.tech@gmail.com',
    signInMethod: 'direct',
    has2FA: false, // Critical SPOF vulnerability!
    twoFactorType: 'none',
    passwordClusterId: 'cluster_casual_shopping',
    permissions: ['contacts', 'photos_storage', 'precise_location'],
    knownBreachesCount: 0,
    sensitivityWeight: 10,
    identityTier: 'tier2_work',
    lastActivityDate: '2026-09-28',
    notes: 'Primary hub. Recovers financial accounts and handles SSO for developer/cloud tools.',
  },
  {
    id: 'acc_chase_bank',
    name: 'Chase Premier Checking & Card',
    serviceCategory: 'financial',
    usernameOrEmail: 'amorgan_banking',
    signInMethod: 'direct',
    recoveryEmailAccountId: 'acc_google_primary',
    recoveryPhone: '+1 (555) 902-3341',
    has2FA: true,
    twoFactorType: 'sms',
    passwordClusterId: 'cluster_unique_vault',
    permissions: ['financial_data', 'precise_location'],
    knownBreachesCount: 0,
    sensitivityWeight: 10,
    identityTier: 'tier1_vault',
    lastActivityDate: '2026-09-30',
    notes: 'Crucial financial asset. Vulnerable if Google email recovery is hijacked.',
  },
  {
    id: 'acc_github_dev',
    name: 'GitHub (Personal & Open Source)',
    serviceCategory: 'work_dev',
    usernameOrEmail: 'alex-morgan-dev',
    signInMethod: 'direct',
    recoveryEmailAccountId: 'acc_google_primary',
    has2FA: true,
    twoFactorType: 'authenticator_app',
    passwordClusterId: 'cluster_unique_vault',
    permissions: ['photos_storage'],
    knownBreachesCount: 0,
    sensitivityWeight: 9,
    identityTier: 'tier2_work',
    lastActivityDate: '2026-09-29',
    notes: 'Houses API tokens, SSH keys, and personal source code.',
  },
  {
    id: 'acc_old_gaming_forum',
    name: 'VortexGaming Community Forum',
    serviceCategory: 'entertainment_gaming',
    usernameOrEmail: 'alex_vortex99',
    signInMethod: 'direct',
    recoveryEmailAccountId: 'acc_google_primary',
    has2FA: false,
    twoFactorType: 'none',
    passwordClusterId: 'cluster_legacy_easy', // Breached password group!
    permissions: [],
    knownBreachesCount: 2,
    lastBreachDate: '2023-04-12',
    sensitivityWeight: 2,
    identityTier: 'tier3_disposable',
    lastActivityDate: '2024-01-10',
    notes: 'Forgotten forum account. Breached twice in database leaks.',
  },
  {
    id: 'acc_dropbox_personal',
    name: 'Dropbox Personal Storage',
    serviceCategory: 'cloud_storage',
    usernameOrEmail: 'alex.morgan.tech@gmail.com',
    signInMethod: 'direct',
    recoveryEmailAccountId: 'acc_google_primary',
    has2FA: false,
    twoFactorType: 'none',
    passwordClusterId: 'cluster_legacy_easy', // Reuses breached password from forum!
    permissions: ['photos_storage'],
    knownBreachesCount: 1,
    sensitivityWeight: 8,
    identityTier: 'tier2_work',
    lastActivityDate: '2026-06-15',
    notes: 'Holds tax scans, ID copies, and lease agreements. Shares password with VortexGaming!',
  },
  {
    id: 'acc_slack_workspace',
    name: 'Consulting Slack Workspaces',
    serviceCategory: 'work_dev',
    usernameOrEmail: 'alex.morgan.tech@gmail.com',
    signInMethod: 'google_sso',
    ssoParentId: 'acc_google_primary',
    has2FA: true,
    twoFactorType: 'authenticator_app',
    passwordClusterId: 'cluster_unique_vault',
    permissions: ['photos_storage', 'contacts'],
    knownBreachesCount: 0,
    sensitivityWeight: 7,
    identityTier: 'tier2_work',
    lastActivityDate: '2026-09-29',
  },
  {
    id: 'acc_spotify_streaming',
    name: 'Spotify Family Plan',
    serviceCategory: 'entertainment_gaming',
    usernameOrEmail: 'alex.morgan.tech@gmail.com',
    signInMethod: 'google_sso',
    ssoParentId: 'acc_google_primary',
    has2FA: false,
    twoFactorType: 'none',
    passwordClusterId: 'cluster_unique_vault',
    permissions: ['photos_storage'],
    knownBreachesCount: 0,
    sensitivityWeight: 3,
    identityTier: 'tier3_disposable',
    lastActivityDate: '2026-09-30',
  },
  {
    id: 'acc_notion_notes',
    name: 'Notion Knowledge Base',
    serviceCategory: 'work_dev',
    usernameOrEmail: 'alex.morgan.tech@gmail.com',
    signInMethod: 'google_sso',
    ssoParentId: 'acc_google_primary',
    has2FA: false,
    twoFactorType: 'none',
    passwordClusterId: 'cluster_unique_vault',
    permissions: ['photos_storage'],
    knownBreachesCount: 0,
    sensitivityWeight: 8,
    identityTier: 'tier2_work',
    lastActivityDate: '2026-09-30',
    notes: 'Holds personal journal, project roadmaps, and unreleased client briefs.',
  },
  {
    id: 'acc_amazon_prime',
    name: 'Amazon Prime Shopping',
    serviceCategory: 'shopping',
    usernameOrEmail: 'alex.morgan.tech@gmail.com',
    signInMethod: 'direct',
    recoveryEmailAccountId: 'acc_google_primary',
    has2FA: false,
    twoFactorType: 'none',
    passwordClusterId: 'cluster_casual_shopping', // Reuses password with Google!
    permissions: ['financial_data', 'precise_location'],
    knownBreachesCount: 0,
    sensitivityWeight: 7,
    identityTier: 'tier3_disposable',
    lastActivityDate: '2026-09-20',
  },
  {
    id: 'acc_steam_games',
    name: 'Steam Gaming Library',
    serviceCategory: 'entertainment_gaming',
    usernameOrEmail: 'shadow_alex_99',
    signInMethod: 'direct',
    recoveryEmailAccountId: 'acc_google_primary',
    has2FA: true,
    twoFactorType: 'authenticator_app',
    passwordClusterId: 'cluster_legacy_easy', // Reuses breached cluster
    permissions: ['financial_data'],
    knownBreachesCount: 0,
    sensitivityWeight: 6,
    identityTier: 'tier3_disposable',
    lastActivityDate: '2026-09-27',
  },
  {
    id: 'acc_flashlight_pro',
    name: 'QuickLight Utility Widget App',
    serviceCategory: 'utility_apps',
    usernameOrEmail: 'device_uuid_849204',
    signInMethod: 'direct',
    has2FA: false,
    twoFactorType: 'none',
    passwordClusterId: 'cluster_unique_vault',
    permissions: [
      'camera',
      'microphone',
      'precise_location',
      'contacts',
      'photos_storage',
      'background_tracking',
    ], // Massive permission abuse!
    knownBreachesCount: 0,
    sensitivityWeight: 4,
    identityTier: 'tier3_disposable',
    lastActivityDate: '2026-09-25',
    notes: 'Shady free utility app requesting invasive hardware permissions.',
  },
  {
    id: 'acc_crypto_vault',
    name: 'ColdStorage / Hardware Ledger Bridge',
    serviceCategory: 'financial',
    usernameOrEmail: '0x9482...e7b1',
    signInMethod: 'direct',
    has2FA: true,
    twoFactorType: 'hardware_key',
    passwordClusterId: 'cluster_unique_vault',
    permissions: [],
    knownBreachesCount: 0,
    sensitivityWeight: 10,
    identityTier: 'tier1_vault',
    lastActivityDate: '2026-09-10',
    notes: 'Well isolated. Hardware 2FA token protected.',
  },
];
